server:
    port: 8084

spring:
    application:
        name: reciping-recipes-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/reciping?serverTimezone=Asia/Seoul
        username: root
        password: root

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${random.value}  # Random ? ??
